# Generated by Django 6.0.2 on 2026-02-27 08:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, default='', max_length=100, verbose_name='კატეგორია')),
                ('title', models.CharField(max_length=200, verbose_name='დასახელება')),
                ('image', models.ImageField(upload_to='products/', verbose_name='ნივთის სურათი')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ფასი')),
                ('release_date', models.DateField(verbose_name='გამოშვების თარიღი')),
                ('brand', models.CharField(max_length=100, verbose_name='ბრენდი')),
                ('stock', models.PositiveIntegerField(verbose_name='საწყობში დარჩენილი რაოდენობა')),
                ('description', models.TextField(verbose_name='დეტალური ინფორმაცია')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='რეიტინგი')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shop.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='შემფასებელი')),
            ],
        ),
    ]
